First two tasks , button sizes and checkbox switcher on fixed mode
1CRM/oceanfront pull request #244
Opened 2023-03-01 10:29 UTC by razinabrahamyan

2023-03-01 18:04 UTC, alexivanenko requested changes
1. A fixed mode for the checkbox: I probably described the task incorrectly but we shouldn't render switch in the fixed mode for checkboxes  but it visually must looks like switch - I mean opacity, grey color, etc.  
<img width="1425" alt="Снимок экрана 2023-03-01 в 20 55 31" src="https://user-images.githubusercontent.com/5743284/222222927-b5ad095f-0489-4c5e-8e9f-953e99b77a59.png">

2. Buttons in a normal size should look like they are now, not smaller or bigger. And the normal size should be a default size in case if the size prop wasn't provided or size="nm"
<img width="1442" alt="Снимок экрана 2023-03-01 в 20 46 51" src="https://user-images.githubusercontent.com/5743284/222223645-976a3f29-ee93-4386-8613-b8a63cd6e0e3.png">
<img width="1437" alt="Снимок экрана 2023-03-01 в 20 46 58" src="https://user-images.githubusercontent.com/5743284/222223720-ae95bce2-8b2a-4da4-b0a4-779fe0b21810.png">

2023-03-02 11:08 UTC, razinabrahamyan commented
got it, working on it

2023-03-06 08:39 UTC, alexivanenko reviewed
Everything just fine. Still need a size property for of-field

2023-03-06 09:03 UTC, alexivanenko approved these changes

2023-03-06 09:05 UTC, merged